
version: '3.4'

services:
  nginx:
    container_name: nf
    image: nf
    privileged: true
    ports:
      - "80:9004"
    volumes:
      - ./nginx:/usr/local/nginx:z
      - ./file:/root/data:z

